import json
import re
import unittest
from pathlib import Path
from .support import ApiCase
try:
    from playwright.sync_api import sync_playwright
except ImportError:
    sync_playwright = None


@unittest.skipIf(sync_playwright is None, 'Install Playwright for browser checks')
class WorkflowBrowser(ApiCase):
    def test_previous_report_preview_preserves_current_inputs(self):
        patient, previous = self.encounter()
        self.ok('report/finalize', {'id': previous['id'], 'report': self.report()}, 'operator')
        self.ok('permission', {'patient_id': patient['id'], 'reason': 'Repeat assessment'}, 'operator')
        current = self.ok('token', {'patient_id': patient['id']}, 'receptionist')
        self.ok('claim', {'id': current['id']}, 'operator2')
        origin = f'http://127.0.0.1:{self.server.server_port}'
        with sync_playwright() as pw:
            browser = pw.chromium.launch(headless=True)
            ctx = browser.new_context(viewport={'width': 1500, 'height': 1050})
            key, value = self.cookies['operator2'].split('=', 1)
            ctx.add_cookies([{'name': key, 'value': value, 'url': origin}])
            page = ctx.new_page()
            page.goto(origin)
            page.wait_for_selector('#logout')
            page.evaluate('id => openEncounter({id, patient_id: ' + str(patient['id']) + '})', current['id'])
            page.wait_for_selector('#doctor')
            page.locator('[data-measure="EF"]').fill('57')
            page.locator('#conclusion').fill('Unsaved current conclusion')
            page.locator('[data-preview-echo]').click()
            self.assertIn('Manual test conclusion', page.locator('dialog').text_content())
            self.assertNotIn('Unsaved current conclusion', page.locator('dialog').text_content())
            page.screenshot(path='artifacts/previous-report-preview.png')
            page.get_by_role('button', name='Close Preview').click()
            self.assertEqual(page.locator('[data-measure="EF"]').input_value(), '57')
            self.assertEqual(page.locator('#conclusion').input_value(), 'Unsaved current conclusion')
            self.assertEqual(page.evaluate('visit.id'), current['id'])
            page.locator('#recordBack').click()
            page.locator('[data-view]').click()
            self.assertIn('Manual test conclusion', page.locator('dialog').text_content())
            page.keyboard.press('Escape')
            page.locator('dialog').wait_for(state='detached')
            self.assertEqual(page.locator('dialog').count(), 0)
            browser.close()

    def test_registration_measurements_correction_and_print(self):
        origin = f'http://127.0.0.1:{self.server.server_port}'
        with sync_playwright() as pw:
            browser = pw.chromium.launch(headless=True)
            errors=[]
            def login(role):
                ctx=browser.new_context(viewport={'width':1500,'height':1050})
                key,value=self.cookies[role].split('=',1)
                ctx.add_cookies([{'name':key,'value':value,'url':origin}])
                page=ctx.new_page();page.on('pageerror',lambda error:errors.append(str(error)))
                page.goto(origin);page.wait_for_selector('#logout')
                page.evaluate("() => { window.print = () => { window.printCalls=(window.printCalls||0)+1; window.imagesReady=[...document.querySelectorAll('#print img')].every(img=>img.complete && img.naturalWidth>0); }; }")
                return page
            reception=login('receptionist')
            reception.locator('[data-go="register"]').click()
            for key,value in {'identity':'1234512345678','phone':'03012345678','name':'Workflow Patient','relation_name':'Test Parent','age':'45'}.items():
                reception.locator(f'#register [name="{key}"]').fill(value)
            reception.locator('#register button').click()
            reception.wait_for_function('window.printCalls === 1')
            self.assertIn('Workflow Patient',reception.locator('#print').text_content())
            self.assertEqual(len(self.ok('state',user='receptionist')['issued']),1)
            patient=self.ok('state',user='receptionist')['patients'][0]
            operator=login('operator')
            operator.locator('[data-start]').first.click();operator.wait_for_selector('#doctor')
            operator.select_option('#doctor',str(self.doc))
            operator.locator('[data-measure="EF"]').fill('61')
            operator.locator('[data-flow="MR"][data-step="1"]').click(click_count=2)
            self.assertEqual(operator.locator('#color').input_value(),'MR ++')
            operator.locator('[data-flow="MR"][data-step="-1"]').click()
            self.assertEqual(operator.locator('#color').input_value(),'MR +')
            operator.locator('[data-new-parameter="dimensions"]').click()
            last=operator.locator('[data-group="dimensions"] [data-parameter-row]').last
            last.locator('[data-cell="0"]').fill('Extra dimension')
            last.locator('[data-cell="1"]').fill('12')
            operator.locator('[data-new-column="dimensions"]').click()
            operator.locator('[data-group="dimensions"] [data-parameter-row]').last.locator('[data-cell="3"]').fill('Manual note')
            operator.screenshot(path='artifacts/workflow-editor.png',full_page=True)
            operator.locator('#save').click();operator.wait_for_selector('[data-draft]')
            operator.locator('[data-draft]').click();operator.wait_for_selector('#doctor')
            self.assertEqual(operator.locator('[data-measure="EF"]').input_value(),'61')
            self.assertEqual(operator.locator('[data-measure="Extra dimension"]').input_value(),'12')
            operator.on('dialog',lambda dialog:dialog.accept())
            operator.get_by_role('button',name='Finalize & Print',exact=True).click()
            operator.wait_for_function('window.printCalls === 1')
            self.assertTrue(operator.evaluate('window.imagesReady'))
            self.assertIn('Manual note',operator.locator('#print').text_content())
            self.assertNotIn('Doppler Parameters',operator.locator('#print').text_content())
            operator.locator('#editReport').click()
            operator.locator('[data-measure="E Wave"]').fill('70')
            operator.locator('[data-measure="A Wave"]').fill('0')
            operator.locator('#conclusion').fill('Corrected manual conclusion')
            operator.locator('#correctionReason').fill('Corrected transcription')
            operator.get_by_role('button',name='Save Correction & Print').click()
            operator.wait_for_function('window.printCalls === 2')
            self.assertIn('Corrected manual conclusion',operator.locator('#print').text_content())
            doppler_print = operator.locator('#print .echo-table').filter(has_text='Doppler Parameters')
            self.assertEqual(doppler_print.locator('tbody tr').count(),2)
            self.assertEqual(doppler_print.locator('tbody tr').nth(0).locator('td').nth(1).text_content(),'70')
            self.assertEqual(doppler_print.locator('tbody tr').nth(1).locator('td').nth(1).text_content(),'0')
            operator.evaluate("document.body.classList.add('printing-report')")
            pdf=operator.pdf(path='artifacts/workflow-report.pdf',prefer_css_page_size=True)
            self.assertEqual(len(re.findall(rb'/Type /Page\b',pdf)),1)
            operator.emulate_media(media='print');operator.screenshot(path='artifacts/workflow-report.png',full_page=True)
            operator.emulate_media(media='screen');operator.evaluate("document.body.classList.remove('printing-report')")
            reception.reload();reception.wait_for_selector('#logout')
            reception.evaluate("() => { window.print=()=>{window.printCalls=(window.printCalls||0)+1}; }")
            reception.evaluate(f'openPatient({patient["id"]})');reception.wait_for_selector('#issue')
            reception.locator('[name="reason"]').fill('Urgent reassessment')
            reception.locator('[name="ordered_by"]').fill('Dr Test')
            reception.locator('#issue button').first.click()
            reception.wait_for_function('window.printCalls === 1')
            self.assertIn('Urgent reassessment',reception.locator('#print').text_content())
            self.assertIn('Dr Test',reception.locator('#print').text_content())
            reception.locator('[data-page="queue"]').click()
            reception.locator('[data-reprint]').last.click();reception.wait_for_function('window.printCalls === 2')
            self.assertIn('Dr Test',reception.locator('#print').text_content())
            reception.evaluate("document.body.classList.add('printing-token')")
            token_pdf=reception.pdf(path='artifacts/workflow-token.pdf',prefer_css_page_size=True)
            self.assertEqual(len(re.findall(rb'/Type /Page\b',token_pdf)),1)
            reception.emulate_media(media='print');reception.screenshot(path='artifacts/workflow-token.png',full_page=True)
            self.assertEqual(errors,[])
            browser.close()

    def test_print_waits_for_images_and_long_report_continues(self):
        patient, visit = self.encounter()
        self.ok('report/finalize', {'id':visit['id'],'report':self.report()}, 'operator')
        origin=f'http://127.0.0.1:{self.server.server_port}'
        with sync_playwright() as pw:
            browser=pw.chromium.launch(headless=True)
            ctx=browser.new_context()
            key,value=self.cookies['operator'].split('=',1)
            ctx.add_cookies([{'name':key,'value':value,'url':origin}])
            page=ctx.new_page();page.goto(origin);page.wait_for_selector('#logout')
            page.evaluate('() => {window.printCalls=0; window.print=()=>{window.printCalls++};}')
            page.evaluate('openEncounter(state.history[0])');page.wait_for_selector('#printReport')
            page.route('**/assets/logo-right.png',lambda route:route.abort())
            page.locator('#printReport').click()
            page.wait_for_function('document.querySelector("#toast").textContent.includes("could not load")')
            self.assertEqual(page.evaluate('window.printCalls'),0)
            page.unroute('**/assets/logo-right.png')
            page.locator('#printReport').click();page.wait_for_function('window.printCalls===1')
            page.evaluate("() => {const r=JSON.parse(visit.report); r.findings=Array.from({length:100},(_,i)=>'Manual report line '+(i+1)).join('\\n');visit.report=JSON.stringify(r);}")
            page.locator('#printReport').click();page.wait_for_function('window.printCalls===2')
            page.evaluate("document.body.classList.add('printing-report')")
            pdf=page.pdf(path='artifacts/workflow-long-report.pdf',prefer_css_page_size=True)
            self.assertGreater(len(re.findall(rb'/Type /Page\b',pdf)),1)
            self.assertIn('Manual report line 100',page.locator('#print').text_content())
            browser.close()
